In [1]:
import pandas as pd
import numpy as np

In [7]:
ori_df=pd.read_csv('./RNA_DATA/nmosd_merge_sort_df.csv')
ori_df

   !Sample_title Sample Name          Run
0        6_C-267  GSM8380151  SRR29718005
1       5_20-377  GSM8380150  SRR29718006
2       4_20-269  GSM8380149  SRR29718007
3       3_19-178  GSM8380148  SRR29718008
4        2_19-42  GSM8380147  SRR29718009
5        1_19-14  GSM8380146  SRR29718010
6       5_20-384  GSM8380145  SRR29718011
7       4_20-316  GSM8380144  SRR29718012
8       3_19-177  GSM8380143  SRR29718013
9       2_19-139  GSM8380142  SRR29718014
10       1_18-42  GSM8380141  SRR29718015
11      5_20-385  GSM8380140  SRR29718016
12       4_19-13  GSM8380139  SRR29718017
13       3_18-20  GSM8380138  SRR29718018
14       2_16-35  GSM8380137  SRR29718019
15       1_15-86  GSM8380136  SRR29718020
16       6_C-621  GSM8380135  SRR29718021
17       5_C-350  GSM8380134  SRR29718022
18      4_19-211  GSM8380133  SRR29718023
19       3_16-47  GSM8380132  SRR29718024
20       2_15-92  GSM8380131  SRR29718025
21       1_14-81  GSM8380130  SRR29718026
22      4_19-203  GSM8380129  SRR29718027
23      3_19-154  GSM8380128  SRR29718028
24       2_19-73  GSM8380127  SRR29718029
25       1_19-07  GSM8380126  SRR29718030
26       3_C-598  GSM8380125  SRR29718031
27       2_C-113  GSM8380124  SRR29718032
28      1_19-180  GSM8380123  SRR29718033
29      4_pt-s96  GSM8380122  SRR29718034
30      3_pt-s91  GSM8380121  SRR29718035
31       2_C-227  GSM8380120  SRR29718036
32       1_C-106  GSM8380119  SRR29718037
33      6_19-158  GSM8380118  SRR29718038
34       5_16-43  GSM8380117  SRR29718039
35       4_15-71  GSM8380116  SRR29718040
36       3_15-58  GSM8380115  SRR29718041
37       2_15-32  GSM8380114  SRR29718042
38       1_15-11  GSM8380113  SRR29718043
39       4_C-593  GSM8380112  SRR29718044
40       3_C-358  GSM8380111  SRR29718045
41       2_C-291  GSM8380110  SRR29718046
42       1_C-153  GSM8380109  SRR29718047
43       4_C-478  GSM8380108  SRR29718048
44       3_C-315  GSM8380107  SRR29718049
45       2_C-229  GSM8380106  SRR29718050
46       1_C-115  GSM8380105  SRR29718051

In [5]:
ref_df=pd.read_csv('./RNA_DATA/rna_correspondence_table_for_samples.csv')
ref_df

   Sample name in GEO Patient Number
0             1_C-115    Patient6_1T
1             2_C-229    Patient6_2T
2             3_C-315    Patient6_3T
3             4_C-478    Patient6_4T
4             1_C-153    Patient5_1T
5             2_C-291    Patient5_2T
6             3_C-358    Patient5_3T
7             4_C-593    Patient5_4T
8             1_15-11    Patient3_1T
9             2_15-32    Patient3_2T
10            3_15-58    Patient3_3T
11            4_15-71    Patient3_4T
12            5_16-43    Patient3_5T
13           6_19-158    Patient3_6T
14            1_C-106   Patient10_1T
15            2_C-227   Patient10_2T
16           3_pt-s91   Patient10_3T
17           4_pt-s96   Patient10_4T
18           1_19-180    Patient8_1T
19            2_C-113    Patient8_2T
20            3_C-598    Patient8_3T
21            1_19-07    Patient2_1T
22            2_19-73    Patient2_2T
23           3_19-154    Patient2_3T
24           4_19-203    Patient2_4T
25            1_14-81    Patient7_1T
26            2_15-92    Patient7_2T
27            3_16-47    Patient7_3T
28           4_19-211    Patient7_4T
29            5_C-350    Patient7_5T
30            6_C-621    Patient7_6T
31            1_15-86    Patient9_1T
32            2_16-35    Patient9_2T
33            3_18-20    Patient9_3T
34            4_19-13    Patient9_4T
35           5_20-385    Patient9_5T
36            1_18-42    Patient1_1T
37           2_19-139    Patient1_2T
38           3_19-177    Patient1_3T
39           4_20-316    Patient1_4T
40           5_20-384    Patient1_5T
41            1_19-14    Patient4_1T
42            2_19-42    Patient4_2T
43           3_19-178    Patient4_3T
44           4_20-269    Patient4_4T
45           5_20-377    Patient4_5T
46            6_C-267    Patient4_6T

In [8]:
ref_df.rename(columns={	'Sample name in GEO':'!Sample_title'},inplace=True)

In [9]:
ref_df

   !Sample_title Patient Number
0        1_C-115    Patient6_1T
1        2_C-229    Patient6_2T
2        3_C-315    Patient6_3T
3        4_C-478    Patient6_4T
4        1_C-153    Patient5_1T
5        2_C-291    Patient5_2T
6        3_C-358    Patient5_3T
7        4_C-593    Patient5_4T
8        1_15-11    Patient3_1T
9        2_15-32    Patient3_2T
10       3_15-58    Patient3_3T
11       4_15-71    Patient3_4T
12       5_16-43    Patient3_5T
13      6_19-158    Patient3_6T
14       1_C-106   Patient10_1T
15       2_C-227   Patient10_2T
16      3_pt-s91   Patient10_3T
17      4_pt-s96   Patient10_4T
18      1_19-180    Patient8_1T
19       2_C-113    Patient8_2T
20       3_C-598    Patient8_3T
21       1_19-07    Patient2_1T
22       2_19-73    Patient2_2T
23      3_19-154    Patient2_3T
24      4_19-203    Patient2_4T
25       1_14-81    Patient7_1T
26       2_15-92    Patient7_2T
27       3_16-47    Patient7_3T
28      4_19-211    Patient7_4T
29       5_C-350    Patient7_5T
30       6_C-621    Patient7_6T
31       1_15-86    Patient9_1T
32       2_16-35    Patient9_2T
33       3_18-20    Patient9_3T
34       4_19-13    Patient9_4T
35      5_20-385    Patient9_5T
36       1_18-42    Patient1_1T
37      2_19-139    Patient1_2T
38      3_19-177    Patient1_3T
39      4_20-316    Patient1_4T
40      5_20-384    Patient1_5T
41       1_19-14    Patient4_1T
42       2_19-42    Patient4_2T
43      3_19-178    Patient4_3T
44      4_20-269    Patient4_4T
45      5_20-377    Patient4_5T
46       6_C-267    Patient4_6T

In [10]:
combined_df=pd.merge(ori_df,ref_df,how='outer',on='!Sample_title')

In [11]:
combined_df

   !Sample_title Sample Name          Run Patient Number
0        1_14-81  GSM8380130  SRR29718026    Patient7_1T
1        1_15-11  GSM8380113  SRR29718043    Patient3_1T
2        1_15-86  GSM8380136  SRR29718020    Patient9_1T
3        1_18-42  GSM8380141  SRR29718015    Patient1_1T
4        1_19-07  GSM8380126  SRR29718030    Patient2_1T
5        1_19-14  GSM8380146  SRR29718010    Patient4_1T
6       1_19-180  GSM8380123  SRR29718033    Patient8_1T
7        1_C-106  GSM8380119  SRR29718037   Patient10_1T
8        1_C-115  GSM8380105  SRR29718051    Patient6_1T
9        1_C-153  GSM8380109  SRR29718047    Patient5_1T
10       2_15-32  GSM8380114  SRR29718042    Patient3_2T
11       2_15-92  GSM8380131  SRR29718025    Patient7_2T
12       2_16-35  GSM8380137  SRR29718019    Patient9_2T
13      2_19-139  GSM8380142  SRR29718014    Patient1_2T
14       2_19-42  GSM8380147  SRR29718009    Patient4_2T
15       2_19-73  GSM8380127  SRR29718029    Patient2_2T
16       2_C-113  GSM8380124  SRR29718032    Patient8_2T
17       2_C-227  GSM8380120  SRR29718036   Patient10_2T
18       2_C-229  GSM8380106  SRR29718050    Patient6_2T
19       2_C-291  GSM8380110  SRR29718046    Patient5_2T
20       3_15-58  GSM8380115  SRR29718041    Patient3_3T
21       3_16-47  GSM8380132  SRR29718024    Patient7_3T
22       3_18-20  GSM8380138  SRR29718018    Patient9_3T
23      3_19-154  GSM8380128  SRR29718028    Patient2_3T
24      3_19-177  GSM8380143  SRR29718013    Patient1_3T
25      3_19-178  GSM8380148  SRR29718008    Patient4_3T
26       3_C-315  GSM8380107  SRR29718049    Patient6_3T
27       3_C-358  GSM8380111  SRR29718045    Patient5_3T
28       3_C-598  GSM8380125  SRR29718031    Patient8_3T
29      3_pt-s91  GSM8380121  SRR29718035   Patient10_3T
30       4_15-71  GSM8380116  SRR29718040    Patient3_4T
31       4_19-13  GSM8380139  SRR29718017    Patient9_4T
32      4_19-203  GSM8380129  SRR29718027    Patient2_4T
33      4_19-211  GSM8380133  SRR29718023    Patient7_4T
34      4_20-269  GSM8380149  SRR29718007    Patient4_4T
35      4_20-316  GSM8380144  SRR29718012    Patient1_4T
36       4_C-478  GSM8380108  SRR29718048    Patient6_4T
37       4_C-593  GSM8380112  SRR29718044    Patient5_4T
38      4_pt-s96  GSM8380122  SRR29718034   Patient10_4T
39       5_16-43  GSM8380117  SRR29718039    Patient3_5T
40      5_20-377  GSM8380150  SRR29718006    Patient4_5T
41      5_20-384  GSM8380145  SRR29718011    Patient1_5T
42      5_20-385  GSM8380140  SRR29718016    Patient9_5T
43       5_C-350  GSM8380134  SRR29718022    Patient7_5T
44      6_19-158  GSM8380118  SRR29718038    Patient3_6T
45       6_C-267  GSM8380151  SRR29718005    Patient4_6T
46       6_C-621  GSM8380135  SRR29718021    Patient7_6T

In [12]:
combined_df_sort = combined_df.sort_values(by='Patient Number')

In [17]:
combined_df_sort

   !Sample_title Sample Name          Run Patient Number
7        1_C-106  GSM8380119  SRR29718037   Patient10_1T
17       2_C-227  GSM8380120  SRR29718036   Patient10_2T
29      3_pt-s91  GSM8380121  SRR29718035   Patient10_3T
38      4_pt-s96  GSM8380122  SRR29718034   Patient10_4T
3        1_18-42  GSM8380141  SRR29718015    Patient1_1T
13      2_19-139  GSM8380142  SRR29718014    Patient1_2T
24      3_19-177  GSM8380143  SRR29718013    Patient1_3T
35      4_20-316  GSM8380144  SRR29718012    Patient1_4T
41      5_20-384  GSM8380145  SRR29718011    Patient1_5T
4        1_19-07  GSM8380126  SRR29718030    Patient2_1T
15       2_19-73  GSM8380127  SRR29718029    Patient2_2T
23      3_19-154  GSM8380128  SRR29718028    Patient2_3T
32      4_19-203  GSM8380129  SRR29718027    Patient2_4T
1        1_15-11  GSM8380113  SRR29718043    Patient3_1T
10       2_15-32  GSM8380114  SRR29718042    Patient3_2T
20       3_15-58  GSM8380115  SRR29718041    Patient3_3T
30       4_15-71  GSM8380116  SRR29718040    Patient3_4T
39       5_16-43  GSM8380117  SRR29718039    Patient3_5T
44      6_19-158  GSM8380118  SRR29718038    Patient3_6T
5        1_19-14  GSM8380146  SRR29718010    Patient4_1T
14       2_19-42  GSM8380147  SRR29718009    Patient4_2T
25      3_19-178  GSM8380148  SRR29718008    Patient4_3T
34      4_20-269  GSM8380149  SRR29718007    Patient4_4T
40      5_20-377  GSM8380150  SRR29718006    Patient4_5T
45       6_C-267  GSM8380151  SRR29718005    Patient4_6T
9        1_C-153  GSM8380109  SRR29718047    Patient5_1T
19       2_C-291  GSM8380110  SRR29718046    Patient5_2T
27       3_C-358  GSM8380111  SRR29718045    Patient5_3T
37       4_C-593  GSM8380112  SRR29718044    Patient5_4T
8        1_C-115  GSM8380105  SRR29718051    Patient6_1T
18       2_C-229  GSM8380106  SRR29718050    Patient6_2T
26       3_C-315  GSM8380107  SRR29718049    Patient6_3T
36       4_C-478  GSM8380108  SRR29718048    Patient6_4T
0        1_14-81  GSM8380130  SRR29718026    Patient7_1T
11       2_15-92  GSM8380131  SRR29718025    Patient7_2T
21       3_16-47  GSM8380132  SRR29718024    Patient7_3T
33      4_19-211  GSM8380133  SRR29718023    Patient7_4T
43       5_C-350  GSM8380134  SRR29718022    Patient7_5T
46       6_C-621  GSM8380135  SRR29718021    Patient7_6T
6       1_19-180  GSM8380123  SRR29718033    Patient8_1T
16       2_C-113  GSM8380124  SRR29718032    Patient8_2T
28       3_C-598  GSM8380125  SRR29718031    Patient8_3T
2        1_15-86  GSM8380136  SRR29718020    Patient9_1T
12       2_16-35  GSM8380137  SRR29718019    Patient9_2T
22       3_18-20  GSM8380138  SRR29718018    Patient9_3T
31       4_19-13  GSM8380139  SRR29718017    Patient9_4T
42      5_20-385  GSM8380140  SRR29718016    Patient9_5T

In [18]:
merge_new_df=pd.concat([combined_df_sort.iloc[4:,:],combined_df_sort.iloc[0:4,:]],axis=0) #axis=0 依據row結合

In [19]:
merge_new_df

   !Sample_title Sample Name          Run Patient Number
3        1_18-42  GSM8380141  SRR29718015    Patient1_1T
13      2_19-139  GSM8380142  SRR29718014    Patient1_2T
24      3_19-177  GSM8380143  SRR29718013    Patient1_3T
35      4_20-316  GSM8380144  SRR29718012    Patient1_4T
41      5_20-384  GSM8380145  SRR29718011    Patient1_5T
4        1_19-07  GSM8380126  SRR29718030    Patient2_1T
15       2_19-73  GSM8380127  SRR29718029    Patient2_2T
23      3_19-154  GSM8380128  SRR29718028    Patient2_3T
32      4_19-203  GSM8380129  SRR29718027    Patient2_4T
1        1_15-11  GSM8380113  SRR29718043    Patient3_1T
10       2_15-32  GSM8380114  SRR29718042    Patient3_2T
20       3_15-58  GSM8380115  SRR29718041    Patient3_3T
30       4_15-71  GSM8380116  SRR29718040    Patient3_4T
39       5_16-43  GSM8380117  SRR29718039    Patient3_5T
44      6_19-158  GSM8380118  SRR29718038    Patient3_6T
5        1_19-14  GSM8380146  SRR29718010    Patient4_1T
14       2_19-42  GSM8380147  SRR29718009    Patient4_2T
25      3_19-178  GSM8380148  SRR29718008    Patient4_3T
34      4_20-269  GSM8380149  SRR29718007    Patient4_4T
40      5_20-377  GSM8380150  SRR29718006    Patient4_5T
45       6_C-267  GSM8380151  SRR29718005    Patient4_6T
9        1_C-153  GSM8380109  SRR29718047    Patient5_1T
19       2_C-291  GSM8380110  SRR29718046    Patient5_2T
27       3_C-358  GSM8380111  SRR29718045    Patient5_3T
37       4_C-593  GSM8380112  SRR29718044    Patient5_4T
8        1_C-115  GSM8380105  SRR29718051    Patient6_1T
18       2_C-229  GSM8380106  SRR29718050    Patient6_2T
26       3_C-315  GSM8380107  SRR29718049    Patient6_3T
36       4_C-478  GSM8380108  SRR29718048    Patient6_4T
0        1_14-81  GSM8380130  SRR29718026    Patient7_1T
11       2_15-92  GSM8380131  SRR29718025    Patient7_2T
21       3_16-47  GSM8380132  SRR29718024    Patient7_3T
33      4_19-211  GSM8380133  SRR29718023    Patient7_4T
43       5_C-350  GSM8380134  SRR29718022    Patient7_5T
46       6_C-621  GSM8380135  SRR29718021    Patient7_6T
6       1_19-180  GSM8380123  SRR29718033    Patient8_1T
16       2_C-113  GSM8380124  SRR29718032    Patient8_2T
28       3_C-598  GSM8380125  SRR29718031    Patient8_3T
2        1_15-86  GSM8380136  SRR29718020    Patient9_1T
12       2_16-35  GSM8380137  SRR29718019    Patient9_2T
22       3_18-20  GSM8380138  SRR29718018    Patient9_3T
31       4_19-13  GSM8380139  SRR29718017    Patient9_4T
42      5_20-385  GSM8380140  SRR29718016    Patient9_5T
7        1_C-106  GSM8380119  SRR29718037   Patient10_1T
17       2_C-227  GSM8380120  SRR29718036   Patient10_2T
29      3_pt-s91  GSM8380121  SRR29718035   Patient10_3T
38      4_pt-s96  GSM8380122  SRR29718034   Patient10_4T

In [20]:
merge_new_df.to_csv("./RNA_DATA/merge_sample_id.csv",index=False)

In [23]:
merge_new_df.loc[:,['Run','Patient Number']].to_csv('./RNA_DATA/sample_run_df.txt',sep=',',index=False)